#!bin/sh
NUM_RUNS=$1
COUNTER=25
#FLUIDDIR="data"
#mkdir $FLUIDDIR
until [ $COUNTER -gt $NUM_RUNS ]; do
	echo $COUNTER
	FLUIDDIR="data/sample_$COUNTER"
	mkdir $FLUIDDIR

	python modify.py $COUNTER

	SU2_CFD lam_cylinder.cfg

	cp -r flow.vtk $FLUIDDIR/flow.vtk

	rm *.vtk

	let COUNTER+=1
done